// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbifymhurfgujuldncmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiaWZ5bWh1cmZndWp1bGRuY21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzI1MDksImV4cCI6MjA2MDA0ODUwOX0.PeGRS01Fq_mL0TKKt-6C_DkftW2KPz1_U04GVramd_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);